version: "3.5"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  database:
    container_name: database.127.0.0.1.xip.io
    image: postgres:11.5
    restart: "on-failure"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keeper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_keeping


  migrate:
    depends_on:
      - database
    image: github.com/jani123/book-keeping
    restart: "on-failure"
    build:
      context: ./
    entrypoint: ""
    command:
      - "/bin/app"
      - "migrate"

  app:
    depends_on:
      - migrate
    image: github.com/jani123/book-keeping
    restart: "on-failure"
    build:
      context: ./
    ports:
      - 80
    environment:
      PORT: 80
      VIRTUAL_HOST: book-keeping.127.0.0.1.xip.io
      VIRTUAL_PORT: 80
    entrypoint: ""
    command:
      - "/bin/app"

networks:
  default:
    name: core-network
