version: "3.5"

services:
  nginx-proxy:
    container_name: book-keeping-proxy.127.0.0.1.nip.io
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  database:
    container_name: database.127.0.0.1.nip.io
    image: postgres:11.5
    restart: "on-failure"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keeper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_keeping
    volumes:
      - database:/var/lib/postgresql/data


  migrate:
    container_name: book-keeping-migrate.127.0.0.1.nip.io
    depends_on:
      - database
    image: github.com/jani123/book-keeping
    restart: "on-failure"
    build:
      context: ./
    entrypoint: ""
    command:
      - "/bin/app"
      - "migrate"

  app:
    container_name: book-keeping.127.0.0.1.nip.io
    depends_on:
      - migrate
    image: github.com/jani123/book-keeping
    restart: "on-failure"
    environment:
      ADDR: 0.0.0.0
      PORT: 3000
      VIRTUAL_HOST: book-keeping.127.0.0.1.nip.io
      VIRTUAL_PORT: 3000
    entrypoint: ""

networks:
  default:
    name: book-keeping-network

volumes:
  database:
    name: book-keeping-db
